# Site settings
title: My Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter_username
github_username:  your_github_username

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# SEO tag configuration
jekyll_seo_tag:
  social:
    name: My Blog
    image: /assets/img/social.jpg
    twitter: your_twitter_username
    github: your_github_username

# Google Analytics
google_analytics: UA-XXXXXXXX-X

# Disqus comments
disqus:
  shortname: your-disqus-shortname

# Other configurations
highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
exclude: ["node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Sitemaps
sitemap:
  exclude: ['atom.xml', '404.html', 'feed.xml']
